language: node_js
dist: trusty
node_js:
    - lts/*
branches:
    only:
        - master
#notifications:
#    email:
#        on_success: change
#        on_failure: always
#    recipients:
script:
    - yarn run lint
    - yarn run build
    - yarn run test --watch=false
after_success:
    - yarn run codecov